export const STRINGS = {
  COMMON: {
    LOADING: 'Loading...',
    RETRY: 'Retry',
    CANCEL: 'Cancel',
    SAVE: 'Save',
    DELETE: 'Delete',
    CONFIRM: 'Confirm',
    BACK: 'Back',
    NEXT: 'Next',
    DONE: 'Done',
    CLOSE: 'Close',
  },
  ERRORS: {
    NETWORK: 'Network error. Please check your connection.',
    GENERIC: 'Something went wrong. Please try again.',
    INVALID_EMAIL: 'Please enter a valid email address',
    PASSWORD_MIN_LENGTH: 'Password must be at least 8 characters',
    REQUIRED_FIELD: 'This field is required',
  },
  HOME: {
    WELCOME: 'Welcome to Expo Template',
    SUBTITLE: 'A production-ready template with best practices',
  },
  AUTH: {
    EMAIL: 'Email',
    PASSWORD: 'Password',
    CONFIRM_PASSWORD: 'Confirm Password',
    NAME: 'Full Name',
    VERIFICATION_CODE: 'Verification Code',

    LOGIN: 'Log In',
    REGISTER: 'Sign Up',
    LOGOUT: 'Log Out',
    FORGOT_PASSWORD: 'Forgot Password?',
    RESET_PASSWORD: 'Reset Password',
    SEND_CODE: 'Send Code',
    VERIFY: 'Verify',
    CONTINUE_WITH_GOOGLE: 'Continue with Google',
    CONTINUE_WITH_APPLE: 'Continue with Apple',

    WELCOME_BACK: 'Welcome back',
    CREATE_ACCOUNT: 'Create your account',
    ALREADY_HAVE_ACCOUNT: 'Already have an account?',
    DONT_HAVE_ACCOUNT: "Don't have an account?",
    RESET_PASSWORD_TITLE: 'Reset your password',
    RESET_PASSWORD_DESC: 'Enter your email to receive a reset code',
    VERIFY_EMAIL_TITLE: 'Verify your email',
    VERIFY_EMAIL_DESC: 'Enter the code sent to your email',
    OR_CONTINUE_WITH: 'Or continue with',

    EMAIL_REQUIRED: 'Email is required',
    EMAIL_INVALID: 'Please enter a valid email address',
    PASSWORD_REQUIRED: 'Password is required',
    PASSWORD_MIN_LENGTH: 'Password must be at least 8 characters',
    PASSWORD_WEAK: 'Password must contain uppercase, lowercase, and number',
    PASSWORD_CONFIRM_REQUIRED: 'Please confirm your password',
    PASSWORD_MISMATCH: 'Passwords do not match',
    NAME_REQUIRED: 'Name is required',
    NAME_MIN_LENGTH: 'Name must be at least 2 characters',
    CODE_REQUIRED: 'Verification code is required',
  },
} as const;
